// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ElcNb-Nn9c54yLayUUs3iUznWnIvQUE',
    appId: '1:297812953491:web:efc94fc7010b4cb2aa4066',
    messagingSenderId: '297812953491',
    projectId: 'quickkart-8499d',
    authDomain: 'quickkart-8499d.firebaseapp.com',
    storageBucket: 'quickkart-8499d.firebasestorage.app',
    measurementId: 'G-PPLGT1M1FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlaG34NFMptphoQ3-w_ENKEgktmuPnYw0',
    appId: '1:297812953491:android:b241a9b6703b49d9aa4066',
    messagingSenderId: '297812953491',
    projectId: 'quickkart-8499d',
    storageBucket: 'quickkart-8499d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-d-R20BT-hnHdTqFcacsYaZdcuI9WrGk',
    appId: '1:297812953491:ios:2a19be97f5bb8cf8aa4066',
    messagingSenderId: '297812953491',
    projectId: 'quickkart-8499d',
    storageBucket: 'quickkart-8499d.firebasestorage.app',
    iosBundleId: 'com.example.eApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-d-R20BT-hnHdTqFcacsYaZdcuI9WrGk',
    appId: '1:297812953491:ios:2a19be97f5bb8cf8aa4066',
    messagingSenderId: '297812953491',
    projectId: 'quickkart-8499d',
    storageBucket: 'quickkart-8499d.firebasestorage.app',
    iosBundleId: 'com.example.eApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ElcNb-Nn9c54yLayUUs3iUznWnIvQUE',
    appId: '1:297812953491:web:352b0d3d3ab77e8baa4066',
    messagingSenderId: '297812953491',
    projectId: 'quickkart-8499d',
    authDomain: 'quickkart-8499d.firebaseapp.com',
    storageBucket: 'quickkart-8499d.firebasestorage.app',
    measurementId: 'G-N8Y9ZNX1F4',
  );
}
